---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["jakubbujny.com"]
    resources: ["jenkinspipelines"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd
subjects:
  - kind: ServiceAccount
    name: cicd
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io